name: CDK Check 

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  AWS_REGION: ap-southeast-1
  CDK_STACK_NAME: WebsiteStack
  CONTEXT_BUCKET_NAME: quang

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm ci

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::669459364263:role/GHA
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: GHA

      - name: Verify identity
        run: aws sts get-caller-identity

      - name: CDK synth
        run: npx cdk synth -c bucketName="${{ env.CONTEXT_BUCKET_NAME }}"

      - name: CDK diff
        run: npx cdk diff ${{ env.CDK_STACK_NAME }} -c bucketName="${{ env.CONTEXT_BUCKET_NAME }}"
